name: Deploy Mattermost Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: teams-runner
    
    steps:
      - name: Fix Git Permissions
        run: sudo chown -R $USER:$USER /home/ubuntu/mattermost/.git 2>/dev/null || true
        
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false
        
      - name: Stop Server
        run: make stop-server
        working-directory: server
          
      - name: Wait for Server to Stop
        run: sleep 3
        
      - name: Start Server
        run: ./start-detached.sh
        working-directory: server
