name: Deploy Mattermost Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: teams-runner
    
    steps:
      - name: Stop Mattermost Service
        run: sudo systemctl stop mattermost
        continue-on-error: true
          
      - name: Pull Latest Changes
        run: |
          cd /home/ubuntu/mattermost-runner/_work/mattermost/mattermost
          git fetch origin
          git reset --hard origin/master
        
      - name: Fix Permissions
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/mattermost-runner
        
      - name: Start Mattermost Service
        run: sudo systemctl start mattermost
